// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/ONSdigital/dp-legacy-cache-proxy/service"
	"net/http"
	"sync"
)

// Ensure, that RequestMiddlewareMock does implement service.RequestMiddleware.
// If this is not the case, regenerate this file with moq.
var _ service.RequestMiddleware = &RequestMiddlewareMock{}

// RequestMiddlewareMock is a mock implementation of service.RequestMiddleware.
//
//	func TestSomethingThatUsesRequestMiddleware(t *testing.T) {
//
//		// make and configure a mocked service.RequestMiddleware
//		mockedRequestMiddleware := &RequestMiddlewareMock{
//			GetMiddlewareFunctionFunc: func() func(http.Handler) http.Handler {
//				panic("mock out the GetMiddlewareFunction method")
//			},
//		}
//
//		// use mockedRequestMiddleware in code that requires service.RequestMiddleware
//		// and then make assertions.
//
//	}
type RequestMiddlewareMock struct {
	// GetMiddlewareFunctionFunc mocks the GetMiddlewareFunction method.
	GetMiddlewareFunctionFunc func() func(http.Handler) http.Handler

	// calls tracks calls to the methods.
	calls struct {
		// GetMiddlewareFunction holds details about calls to the GetMiddlewareFunction method.
		GetMiddlewareFunction []struct {
		}
	}
	lockGetMiddlewareFunction sync.RWMutex
}

// GetMiddlewareFunction calls GetMiddlewareFunctionFunc.
func (mock *RequestMiddlewareMock) GetMiddlewareFunction() func(http.Handler) http.Handler {
	if mock.GetMiddlewareFunctionFunc == nil {
		panic("RequestMiddlewareMock.GetMiddlewareFunctionFunc: method is nil but RequestMiddleware.GetMiddlewareFunction was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetMiddlewareFunction.Lock()
	mock.calls.GetMiddlewareFunction = append(mock.calls.GetMiddlewareFunction, callInfo)
	mock.lockGetMiddlewareFunction.Unlock()
	return mock.GetMiddlewareFunctionFunc()
}

// GetMiddlewareFunctionCalls gets all the calls that were made to GetMiddlewareFunction.
// Check the length with:
//
//	len(mockedRequestMiddleware.GetMiddlewareFunctionCalls())
func (mock *RequestMiddlewareMock) GetMiddlewareFunctionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetMiddlewareFunction.RLock()
	calls = mock.calls.GetMiddlewareFunction
	mock.lockGetMiddlewareFunction.RUnlock()
	return calls
}
